version: '3.8'

services:
  iot-camera:
    image: iot/smart-garage:desktop  # Replace with a custom image if needed
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - "/dev/video0:/dev/video0"  # Mount the Raspberry Pi camera device
    environment:
      - MQTT_BROKER=raspi-mqtt.local  # Replace with your MQTT broker's hostname or IP
      - MQTT_PORT=1883
      - CAMERA_DEVICE=/dev/video0
    volumes:
      - .:/ws  # Mount application code
    working_dir: /ws
    command: python3 main.py  # Replace with your IoT camera application
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge

